server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: cotation_service_v1
          #uri: 'http://localhost:8081'
          uri: 'http://cotation-service.default.svc.cluster.local:80'
          predicates:
            - Path=/cotation/**
        - id: real_estate_service_v2
          uri: 'http://localhost:8082'
          predicates:
            - Path=/realEstates/**
#backEndURL: http://back-end-service.default.svc.cluster.local:80/hello
